-- destrukce.sql
-- Smaze vsechny objekty v opacnem poradi, nez byly vytvoreny

-- 1. Triggery (mažou se automaticky s tabulkami, ale pro jistotu)
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_hra_pred_vlozenim'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_tah_pred_vlozenim'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_tah_po_vlozeni'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_hra_po_zmene_stavu'; EXCEPTION WHEN OTHERS THEN NULL; END; /

-- 2. Pohledy
BEGIN EXECUTE IMMEDIATE 'DROP VIEW PAPIR'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VYHRY_ZACINAJICI'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP VIEW REMIZY'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP VIEW PROHRY_ZACINAJICI'; EXCEPTION WHEN OTHERS THEN NULL; END; /

-- 3. Procedury
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE ZABRAN_TAHU'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE ZABRAN_HRE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE KONEC_HRY'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE STATISTIKY'; EXCEPTION WHEN OTHERS THEN NULL; END; /

-- 4. Funkce
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION RADEK_PAPIRU'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION SPATNY_PARAMETR'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION VYHRA'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION HERNI_CAS'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION REMIZA'; EXCEPTION WHEN OTHERS THEN NULL; END; /

-- 5. Tabulky (odkazujici prvni)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TAH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HRA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE OMEZENI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STAV CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HRAC CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END; /