-- HRAC musí být první, protože na něj odkazují ostatní tabulky
CREATE TABLE HRAC (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jmeno        VARCHAR2(100) NOT NULL,
  vyhry_zac    NUMBER DEFAULT 0 NOT NULL,
  prohry_zac   NUMBER DEFAULT 0 NOT NULL,
  remizy_zac   NUMBER DEFAULT 0 NOT NULL,
  vyhry_druhy  NUMBER DEFAULT 0 NOT NULL,
  prohry_druhy NUMBER DEFAULT 0 NOT NULL,
  remizy_druhy NUMBER DEFAULT 0 NOT NULL,
  created_at   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_hrac_jmeno UNIQUE (jmeno)
);

CREATE TABLE STAV (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kod    VARCHAR2(30) NOT NULL,
  popis  VARCHAR2(200) NOT NULL,
  CONSTRAINT uq_stav_kod UNIQUE (kod)
);

CREATE TABLE OMEZENI (
  kod     VARCHAR2(30) PRIMARY KEY,
  min_hod NUMBER NOT NULL,
  max_hod NUMBER NOT NULL,
  CONSTRAINT ck_omezeni_minmax CHECK (min_hod <= max_hod)
);

CREATE TABLE HRA (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sirka             NUMBER NOT NULL,
  vyska             NUMBER NOT NULL,
  delka_rady        NUMBER NOT NULL,
  hrac_x_id         NUMBER NOT NULL,
  hrac_o_id         NUMBER NOT NULL,
  zacina_symbol     CHAR(1) NOT NULL,
  stav_id           NUMBER NOT NULL,
  cas_x_s           NUMBER DEFAULT 0, -- Přidáno default 0 pro výpočty
  cas_o_s           NUMBER DEFAULT 0,
  created_at        DATE DEFAULT SYSDATE NOT NULL,
  finished_at       DATE,
  CONSTRAINT fk_hra_hrac_x FOREIGN KEY (hrac_x_id) REFERENCES HRAC(id),
  CONSTRAINT fk_hra_hrac_o FOREIGN KEY (hrac_o_id) REFERENCES HRAC(id),
  CONSTRAINT fk_hra_stav   FOREIGN KEY (stav_id)   REFERENCES STAV(id),
  CONSTRAINT ck_hra_zacina CHECK (zacina_symbol IN ('X','O')),
  CONSTRAINT ck_hra_hraci  CHECK (hrac_x_id <> hrac_o_id)
  -- Rozměry papíru 5-20 a řady 5-15 bude hlídat SPATNY_PARAMETR/trigger, 
  -- ale tato DB kontrola je dobrý bonus navíc.
);

CREATE TABLE TAH (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hra_id     NUMBER NOT NULL,
  hrac_id    NUMBER NOT NULL,
  radek      NUMBER NOT NULL,
  sloupec    NUMBER NOT NULL,
  played_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Lepší TIMESTAMP pro přesné sekundy
  CONSTRAINT fk_tah_hra  FOREIGN KEY (hra_id)  REFERENCES HRA(id) ON DELETE CASCADE,
  CONSTRAINT fk_tah_hrac FOREIGN KEY (hrac_id) REFERENCES HRAC(id),
  CONSTRAINT uq_tah_pole UNIQUE (hra_id, radek, sloupec)
);